#!/bin/bash
# OpenCraftShop Test Suite
# Runs various tests and generates output for documentation

set -e  # Exit on error

# Colors for output
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo "==================================="
echo "OpenCraftShop Test Suite"
echo "==================================="
echo ""

# Create test results directory
mkdir -p tests/results
TEST_RESULTS="tests/results/test_output_$(date +%Y%m%d_%H%M%S).txt"

# Function to log results
log_result() {
    echo "$1" | tee -a "$TEST_RESULTS"
}

# Function to run a test
run_test() {
    local test_name="$1"
    local test_command="$2"
    
    echo -e "${YELLOW}Running: $test_name${NC}"
    log_result "## Test: $test_name"
    log_result "Command: $test_command"
    log_result "---"
    
    if eval "$test_command" >> "$TEST_RESULTS" 2>&1; then
        echo -e "${GREEN}✓ PASSED${NC}"
        log_result "Result: PASSED"
    else
        echo -e "${RED}✗ FAILED${NC}"
        log_result "Result: FAILED"
        exit 1
    fi
    
    log_result ""
    echo ""
}

# Start tests
log_result "Test Run: $(date)"
log_result "=================================="
log_result ""

# Test 1: Docker build
run_test "Docker Build" "docker-compose build"

# Test 2: Basic workbench generation
run_test "Workbench Generation" "docker-compose run --rm opencraftshop --type workbench --no-visualize"

# Test 3: Check output files exist
run_test "Output Files Check" "ls -la output/workbench.stl output/cut_list.txt output/shopping_list.txt"

# Test 4: Bookshelf with custom dimensions
run_test "Custom Bookshelf" "docker-compose run --rm opencraftshop --type bookshelf --height 48 --width 10 --no-visualize"

# Test 5: Validate JSON output
run_test "JSON Validation" "python3 -m json.tool output/cut_list.json > /dev/null"

# Test 6: Check optimization efficiency
run_test "Optimization Check" "grep -E 'efficiency|Efficiency' output/cut_list.txt"

# Test 7: Price calculation
run_test "Price Calculation" "grep -E 'Total:|TOTAL:' output/shopping_list.txt"

# Test 8: All furniture types
for furniture in workbench storage_bench bed_frame bookshelf; do
    run_test "Generate $furniture" "docker-compose run --rm opencraftshop --type $furniture --no-visualize"
done

# Summary
echo "==================================="
echo -e "${GREEN}All tests passed!${NC}"
echo "Test results saved to: $TEST_RESULTS"
echo "==================================="

# Create summary file
SUMMARY_FILE="tests/results/LATEST_TEST_SUMMARY.md"
cat > "$SUMMARY_FILE" << EOF
# Latest Test Results

**Date**: $(date)  
**Status**: All tests passed ✓

## Tests Executed:
1. Docker Build
2. Workbench Generation
3. Output Files Check
4. Custom Bookshelf
5. JSON Validation
6. Optimization Check
7. Price Calculation
8. All Furniture Types

## Sample Output Efficiency:
$(grep -A2 "SUMMARY:" output/cut_list.txt | tail -n 3)

## Sample Cost:
$(grep "ESTIMATED TOTAL:" output/shopping_list.txt)

---
*Generated by OpenCraftShop Test Suite*
EOF

echo "Summary saved to: $SUMMARY_FILE"